[display]
fullscreen = true
monitor = 1
fps_limit = 30
vsync = true
debug_overlay = true
resolution = [3840, 1080]  # Force specific resolution for testing
#background_color = [0, 0, 255, 255]   # Background color (blue, RGBA) for debugging layer compositing

[panorama]
enabled = true
rescale = "width"  # Changed to shortest so we can see the entire panorama
output_width = 11520 # 5760,11520  # 6x 1920 for 6 projectors total (includes mirroring)
output_height = 1080
blur = true
start_blur = 30.0
end_blur = 0.0
blur_duration = 20
mirror = true

[panorama.tiles]
width = 1920  # Smaller tiles to see more of them
height = 1080
fade_duration = 3.0

[zmq.subscriber]
address = "tcp://localhost"
port = 5555
topics = ["DisplayMedia"]

[title_screen]
enabled = true 
text = "Feed the Fires"           # Text to display
duration = 10.0               # Duration in seconds
fade_out_duration = 10.0      # Fade out duration in seconds
